config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', as: 'user'

  resources :posts
  get 'feed', to: 'posts#feed'

  resources :comments

  post '/users/:id/follow', to: 'follows#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'follows#unfollow', as: 'unfollow_user'

  resources :tags

  post '/posts/:id/like', to: 'likes#like', as: 'like_post'
  post '/posts/:id/unlike', to: 'likes#unlike', as: 'unlike_post'
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { minimum: 2, maximum: 26 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 26 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :received_follows, foreign_key: :followee_id, class_name: "Follow"
  has_many :followers, through: :received_follows, source: :follower, dependent: :destroy
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :given_follows, source: :followee, dependent: :destroy
  
  has_many :given_likes, foreign_key: :user_id, class_name: "Like"
  has_many :liked, through: :given_likes, source: :post, dependent: :destroy
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "missing_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def full_name
    "#{self.first_name} #{self.last_name}".titleize
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @users = User.all
    if Follow.count > 0
      most_followed_id = Follow.group('followee_id').order('COUNT(*) DESC').select('followee_id').limit(1).first
      @most_followed = User.find(most_followed_id.followee_id)
    else
      @most_followed = User.first
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-12">
      <div class="header shadow-lg"><h2 class="text-center">Users</h2>

        <% if @users.count > 0 %>
          <% @users.each do |user| %>
            <div class="sections shadow-lg">
              <div class="row section-header">
                <div class="col-xs-4">
                  <%= image_tag user.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail" %>
                </div>
                <div class="col-xs-4 section-info">
                  <div><strong><%= link_to user.full_name, user_path(user), class: "link-custom" %></strong></div>
                  <div>Joined <%= time_ago_in_words(user.created_at) %> ago</div>
                  <div><%= user.followers.count %> followers</div>
                  <% if user_signed_in? %>
                    <% if current_user != user %>
                      <% if current_user.followings.include?(user) %>
                        <%= link_to '<i class="fa fa-user-times"></i> Unfollow'.html_safe, unfollow_user_path(user), method: :post, class: "link-custom" %>
                      <% else %>
                        <%= link_to '<i class="fa fa-user-plus"></i> Follow'.html_safe, follow_user_path(user), method: :post, class: "link-custom" %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="sections shadow-lg">
            There are no users...
          </div>
        <% end %>
      </div>
    </div>

    <% if @most_followed != nil %>
      <div class="col-md-4 col-12">
        <div class="header shadow-lg"><h2 class="text-center">Most Followed</h2>
          <div class="sections shadow-lg">
            <div class="row section-header">
              <div class="col-xs-4">
                <%= link_to image_tag(@most_followed.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail"), user_path(@most_followed) %>
              </div>
              <div class="col-xs-4 section-info">
                <div><strong><%= link_to @most_followed.full_name, user_path(@most_followed), class: "link-custom" %></strong></div>
                <div>Joined <%= time_ago_in_words(@most_followed.created_at) %> ago</div>
                <div><%= @most_followed.followers.count %> followers</div>
                <% if user_signed_in? %>
                  <% if current_user != @most_followed %>
                    <% if current_user.followings.include?(@most_followed) %>
                      <%= link_to '<i class="fa fa-user-times"></i> Unfollow'.html_safe, unfollow_user_path(@most_followed), method: :post, class: "link-custom" %>
                    <% else %>
                      <%= link_to '<i class="fa fa-user-plus"></i> Follow'.html_safe, follow_user_path(@most_followed), method: :post, class: "link-custom" %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-12">
      <div class="header shadow-lg"><h2 class="text-center"><%= @user.full_name %></h2>
        <div class="row justify-content-center custom-spacing"><%= image_tag @user.avatar.url(:medium), onerror: "this.src='/assets/missing_medium.png'", class: "img-fluid img-thumbnail" %></div>
        <div class="custom-spacing"><i class="fa fa-envelope"></i> <%= @user.email %></div>
        <div class="custom-spacing">Joined <%= time_ago_in_words(@user.created_at) %> ago</div>
        <hr>
        <div class="custom-spacing"><%= @user.followers.count %> followers</div>
        <% if current_user != @user %>
          <% if current_user.followings.include?(@user) %>
            <%= link_to '<i class="fa fa-user-times"></i> Unfollow'.html_safe, unfollow_user_path(@user), method: :post, class: "link-custom" %>
          <% else %>
            <%= link_to '<i class="fa fa-user-plus"></i> Follow'.html_safe, follow_user_path(@user), method: :post, class: "link-custom" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 col-12">
      <div class="header shadow-lg"><h2 class="text-center"><%= @user.first_name %>'s Posts</h2>
        <%= render 'posts/list', obj: @posts %>
      </div>
    </div>
  </div>
</div>