config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', as: 'user'

  resources :posts
  get 'feed', to: 'posts#feed'

  resources :comments

  post '/users/:id/follow', to: 'follows#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'follows#unfollow', as: 'unfollow_user'

  resources :tags

  post '/posts/:id/like', to: 'likes#like', as: 'like_post'
  post '/posts/:id/unlike', to: 'likes#unlike', as: 'unlike_post'
end 

app/models/tag.rb
class Tag < ApplicationRecord
  validates :post_id, presence: true
  validates :content, presence: true, length: { minimum: 2, maximum: 26 }

  belongs_to :post
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    redirect_to posts_path
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @post = Post.find(params[:post_id])
    @tag.post = @post
    if !@post.tags.include?(@tag) and @tag.save
      flash[:notice] ="Tag was successfully created."
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @post = @tag.post
    @tag.destroy
    flash[:notice] ="Tag was successfully deleted."
    redirect_to post_path(@post)
  end

  private
    def tag_params
      params.require(:tag).permit(:content)
    end
end

app/views/tags/new.html.erb
<%= render 'shared/errors', obj: @tag %>

<div class="d-flex justify-content-center align-items-center min-vh-100">
  <div class="container form">
    <div class="row">
      <div class="col-12">
        <div class="header shadow-lg"><h2 class="text-center">Create tag</h2>
          <div class="sections shadow-lg">
            <%= form_for(@tag, url: tags_path(:post_id => params[:post_id])) do |f| %>
              <div class="form-group">
                <%= f.label :content %>
                <%= f.text_field :content, class: "form-control" %>
              </div>
              <%= f.submit class: "btn btn-custom" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>