config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', as: 'user'

  resources :posts
  get 'feed', to: 'posts#feed'

  resources :comments

  post '/users/:id/follow', to: 'follows#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'follows#unfollow', as: 'unfollow_user'

  resources :tags

  post '/posts/:id/like', to: 'likes#like', as: 'like_post'
  post '/posts/:id/unlike', to: 'likes#unlike', as: 'unlike_post'
end 

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  validates :user_id, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :received_likes, foreign_key: :post_id, class_name: "Like"
  has_many :likes, through: :received_likes, source: :user, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @posts = Post.all
    if Like.count > 0
      most_liked_id = Like.group('post_id').order('COUNT(*) DESC').select('post_id').limit(1).first
      @most_liked = Post.find(most_liked_id.post_id)
    else
      @most_liked = Post.first
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] ="Post was successfully created."
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] ="Post was successfully updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] ="Post was successfully deleted."
    redirect_to posts_path
  end

  def feed
    @posts = Post.all
  end

  private
    def post_params
      params.require(:post).permit(:title, :description)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def require_same_user
      if current_user != @post.user
        flash[:alert] ="You don't have permission to access this page."
        redirect_to root_path
      end
    end
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 10 %>
  </div>
  <%= f.submit class: "btn btn-custom"%>
<% end %>

app/views/posts/_list.html.erb
<% obj.each do |post| %>
  <div class="sections shadow-lg">
    <div class="row section-header">
      <div class="col-xs-4">
        <%= link_to image_tag(post.user.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail"), user_path(post.user) %>
      </div>
      <div class="col-xs-4 section-info">
        <div><strong><%= link_to post.user.full_name, user_path(post.user), class: "link-custom" %></strong></div>
        <div><%= time_ago_in_words(post.created_at) %> ago * <i class="fa fa-globe"></i></div>
      </div>
    </div>

    <div><h4><%= link_to post.title, post_path(post), class: "link-custom" %></h4></div>
    <div class="custom-spacing"><%= post.description %></div>
    <hr>
    <div class="custom-spacing"><%= post.likes.count %> likes</div>
    <% if user_signed_in? %>
      <span class="section-actions">
        <% if current_user.liked.include?(post) %>
          <%= link_to '<i class="fa fa-thumbs-up"></i> Unlike'.html_safe, unlike_post_path(post), method: :post, class: "link-custom" %>
        <% else %>
          <%= link_to '<i class="fa fa-thumbs-o-up"></i> Like'.html_safe, like_post_path(post), method: :post, class: "link-custom" %>
        <% end %>
      </span>
      <span><%= link_to '<i class="fa fa-comment"></i> Comment'.html_safe, new_comment_path(:post_id => post), class: "link-custom" %></span>
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="d-flex justify-content-center align-items-center min-vh-100">
  <div class="container form">
    <div class="row">
      <div class="col-12">
        <div class="header shadow-lg"><h2 class="text-center">Edit post</h2>
          <div class="sections shadow-lg">
            <%= render 'posts/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/feed.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-12">
      <div class="header shadow-lg"><h2 class="text-center">Feed</h2>
        <% if current_user.followings.count > 0 %>
          <% temp = false %>
          <% @posts.each do |post| %>
            <% if current_user.followings.include?(post.user) %>
              <% temp = true %>
              <div class="sections shadow-lg">
                <div class="row section-header">
                  <div class="col-xs-4">
                    <%= link_to image_tag(post.user.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail"), user_path(post.user) %>
                  </div>
                  <div class="col-xs-4 section-info">
                    <div><strong><%= link_to post.user.full_name, user_path(post.user), class: "link-custom" %></strong></div>
                    <div><%= time_ago_in_words(post.created_at) %> ago * <i class="fa fa-globe"></i></div>
                  </div>
                </div>
                <h4><%= link_to post.title, post_path(post), class: "link-custom" %></h4>
                <div class="custom-spacing"><%= post.description %></div>
                <hr>
                <div class="custom-spacing"><%= post.likes.count %> likes</div>
                <span class="section-actions">
                <% if current_user.liked.include?(post) %>
                  <%= link_to '<i class="fa fa-thumbs-up"></i> Unlike'.html_safe, unlike_post_path(post), method: :post, class: "link-custom" %>
                <% else %>
                  <%= link_to '<i class="fa fa-thumbs-o-up"></i> Like'.html_safe, like_post_path(post), method: :post, class: "link-custom" %>
                <% end %>
                </span>
                <span><%= link_to '<i class="fa fa-comment"></i> Comment'.html_safe, new_comment_path(:post_id => post), class: "link-custom" %></span>
              </div>
            <% end %>
          <% end %>
          <% if temp == false %>
            <div class="sections shadow-lg">
              The users you've followed haven't made any posts...
            </div>
          <% end %>

        <% else %>
          <div class="sections shadow-lg">
            You aren't following anyone...
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-12">
      <div class="header shadow-lg"><h2 class="text-center">Posts</h2>
        <% if @posts.count > 0 %>
          <%= render 'posts/list', obj: @posts %>
        <% else %>
          <div class="sections shadow-lg">
            There are no posts...
          </div>
        <% end %>
      </div>
    </div>
    
    <% if @most_liked != nil %>
      <div class="col-md-4 col-12">
        <div class="header shadow-lg"><h2 class="text-center">Most Liked</h2>
          <div class="sections shadow-lg">
            <div class="row section-header">
              <div class="col-xs-4">
                <%= link_to image_tag(@most_liked.user.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail"), user_path(@most_liked.user) %>
              </div>
              <div class="col-xs-4 section-info">
                <div><strong><%= link_to @most_liked.user.full_name, user_path(@most_liked.user), class: "link-custom" %></strong></div>
                <div><%= time_ago_in_words(@most_liked.created_at) %> ago * <i class="fa fa-globe"></i></div>
              </div>
            </div>

            <h4><%= link_to @most_liked.title, post_path(@most_liked), class: "link-custom" %></h4>
            <div class="custom-spacing"><%= @most_liked.description %></div>
            <hr>
            <div class="custom-spacing"><%= @most_liked.likes.count %> likes</div>
            <% if user_signed_in? %>
              <span class="section-actions">
                <% if current_user.liked.include?(@most_liked) %>
                  <%= link_to '<i class="fa fa-thumbs-up"></i> Unlike'.html_safe, unlike_post_path(@most_liked), method: :post, class: "link-custom" %>
                <% else %>
                  <%= link_to '<i class="fa fa-thumbs-o-up"></i> Like'.html_safe, like_post_path(@most_liked), method: :post, class: "link-custom" %>
                <% end %>
              </span>
              <span><%= link_to '<i class="fa fa-comment"></i> Comment'.html_safe, new_comment_path(:post_id => @most_liked), class: "link-custom" %></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="d-flex justify-content-center align-items-center min-vh-100">
  <div class="container form">
    <div class="row">
      <div class="col-12">
        <div class="header shadow-lg"><h2 class="text-center">Create post</h2>
          <div class="sections shadow-lg">
            <%= render 'posts/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-12">
      <div class="header shadow-lg"><h2 class="text-center"><%= @post.title %></h2>
        <div class="sections shadow-lg">
          <div class="row section-header">
            <div class="col-xs-4">
              <%= link_to image_tag(@post.user.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail"), user_path(@post.user) %>
            </div>
            <div class="col-xs-4 section-info">
              <div><strong><%= link_to @post.user.full_name, user_path(@post.user), class: "link-custom" %></strong></div>
              <div><%= time_ago_in_words(@post.created_at) %> ago * <i class="fa fa-globe"></i></div>
            </div>
          </div>
          <p><%= @post.description %></p>
          <% if current_user == @post.user %>
            <span class="section-actions"><%= link_to '<i class="fa fa-pencil-square"></i> Edit'.html_safe, edit_post_path(@post), class: "link-custom" %></span>
            <span><%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"}, class: "link-custom" %></span>
          <% end %>

          <hr>
          <div class="custom-spacing">
            <% @post.tags.each do |tag| %>
              <span class="badge badge-custom section-actions"><%= tag.content %>
                <% if current_user == @post.user %>
                  <%= link_to '<i class="fa fa-trash"></i>'.html_safe, tag_path(tag), method: :delete, data: {confirm: "Are you sure you want to delete this tag?"}, class: "badge-link-custom" %>
                <% end %>
              </span>
            <% end %>
          </div>

          <div class="custom-spacing"><%= @post.likes.count %> likes</div>
          <span class="section-actions">
            <% if current_user.liked.include?(@post) %>
              <%= link_to '<i class="fa fa-thumbs-up"></i> Unlike'.html_safe, unlike_post_path(@post), method: :post, class: "link-custom" %>
            <% else %>
              <%= link_to '<i class="fa fa-thumbs-o-up"></i> Like'.html_safe, like_post_path(@post), method: :post, class: "link-custom" %>
            <% end %>
          </span>

          <% if current_user == @post.user %>
            <%= link_to "Add Tag", new_tag_path(:post_id => @post), class: "link-custom" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-12">
      <div class="header shadow-lg"><h2 class="text-center">Comments</h2>
        <%= link_to '<i class="fa fa-comment"></i> Add comment'.html_safe, new_comment_path(:post_id => @post), class: "link-custom" %>
        <% @post.comments.each do |comment| %>
          <div class="sections shadow-lg">
            <div class="row section-header">
              <div class="col-xs-4">
                <%= link_to image_tag(comment.user.avatar.url(:thumb), onerror: "this.src='/assets/missing_thumb.png'", class: "img-fluid img-thumbnail"), user_path(comment.user) %>
              </div>
              <div class="col-xs-4 section-info">
                <div><strong><%= link_to comment.user.full_name, user_path(comment.user), class: "link-custom" %></strong></div>
                <div><%= time_ago_in_words(comment.created_at) %> ago * <i class="fa fa-globe"></i></div>
              </div>
            </div>
            <div class="custom-spacing"><%= comment.content %></div>
            <% if current_user == comment.user %>
              <span class="section-actions"><%= link_to '<i class="fa fa-pencil-square"></i> Edit'.html_safe, edit_comment_path(comment), class: "link-custom" %></span>
              <span><%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, comment_path(comment), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"}, class: "link-custom" %></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>