config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', as: 'user'

  resources :posts
  get 'feed', to: 'posts#feed'

  resources :comments

  post '/users/:id/follow', to: 'follows#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'follows#unfollow', as: 'unfollow_user'

  resources :tags

  post '/posts/:id/like', to: 'likes#like', as: 'like_post'
  post '/posts/:id/unlike', to: 'likes#unlike', as: 'unlike_post'
end 

app/views/layouts/_footer.html.erb
<footer class="footer theme-1">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <span>Fusce ultricies elit ut nulla luctus, vestibulum vulputate lacus rhoncus. Nullam eu ligula a nisl laoreet vestibulum ut at metus. Donec rutrum quam a nisl placerat gravida. Praesent dui eros, interdum vitae dapibus a, tempus in dolor.</span>
      </div>
      <div class="col-4">
        <span>Fusce ultricies elit ut nulla luctus, vestibulum vulputate lacus rhoncus. Nullam eu ligula a nisl laoreet vestibulum ut at metus. Donec rutrum quam a nisl placerat gravida. Praesent dui eros, interdum vitae dapibus a, tempus in dolor.</span>
      </div>
      <div class="col-4">
        <%= link_to '<i class="fa fa-info-circle"></i> About'.html_safe, about_path, class: "footer-link" %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark theme-1">
  <div class="container">
    <%= link_to '<i class="fa fa-user-circle"></i> CRUD-Media'.html_safe, root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
            </a>
            <div class="dropdown-menu theme-2 shadow-lg" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Create Post", new_post_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "View Feed", feed_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to '<i class="fa fa-sign-out"></i> Log out'.html_safe, destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li>
            <%= link_to '<i class="fa fa-sign-in"></i> Log in'.html_safe, user_session_path, class: "nav-link ml-2" %>
          </li>
          <li>
            <%= link_to '<i class="fa fa-clipboard"></i> Sign up'.html_safe, new_user_registration_path, class: "nav-link ml-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD-Media</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  </head>

  <body class="theme-2">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="min-vh-100">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>